name: Setup Terraform

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:

jobs:
  setup-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up HashiCorp GPG key
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

      - name: Add HashiCorp repository
        run: |
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

      - name: Update apt-get and install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Verify Terraform installation
        run: terraform version

      - name: Display Terraform help output
        run: |
          echo "Terraform help output:"
          terraform -help
