name: Setup and Verify Terraform

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:

env:
  TERRAFORM_VERSION: 1.4.7

jobs:
  setup-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Verify Terraform installation
        run: terraform version

      - name: Display Terraform help output
        run: |
          echo "Terraform help output:"
          terraform -help
